events {}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/conf/server.crt;
        ssl_certificate_key /etc/nginx/conf/server.key;

        location / {
            proxy_pass http://frontend:8080;
        }

        location /api/ {
            proxy_pass http://backend:8000/;
        }

        location /ws/ {
            proxy_pass http://backend:8000/;
        }
    }
}
