"""made rooms table/service

Revision ID: 6a71e4b0f9f6
Revises: 752d978b91a9
Create Date: 2026-08-26 05:26:48.719840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a71e4b0f9f6'
down_revision: Union[str, Sequence[str], None] = '752d978b91a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_friendships_receiver_status', 'friendships', ['receiver_id', 'status'], unique=True)
    op.create_index('ix_friendships_sender_status', 'friendships', ['sender_id', 'status'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friendships_sender_status', table_name='friendships')
    op.drop_index('ix_friendships_receiver_status', table_name='friendships')
    # ### end Alembic commands ###
