"""renamed friendships columns

Revision ID: 752d978b91a9
Revises: cf73c5e617e1
Create Date: 2026-08-17 04:32:39.085079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752d978b91a9'
down_revision: Union[str, Sequence[str], None] = 'cf73c5e617e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('sender_id', sa.BigInteger(), nullable=False))
    op.add_column('friendships', sa.Column('receiver_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('friendships_user_id_fkey'), 'friendships', type_='foreignkey')
    op.drop_constraint(op.f('friendships_friend_id_fkey'), 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['receiver_id'], ['id'])
    op.drop_column('friendships', 'user_id')
    op.drop_column('friendships', 'friend_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('friend_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('friendships', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key(op.f('friendships_friend_id_fkey'), 'friendships', 'users', ['friend_id'], ['id'])
    op.create_foreign_key(op.f('friendships_user_id_fkey'), 'friendships', 'users', ['user_id'], ['id'])
    op.drop_column('friendships', 'receiver_id')
    op.drop_column('friendships', 'sender_id')
    # ### end Alembic commands ###
