"""added invites table

Revision ID: 9f963a409c0b
Revises: baa388a2a118
Create Date: 2026-08-29 04:31:02.525249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f963a409c0b'
down_revision: Union[str, Sequence[str], None] = 'baa388a2a118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('invitee_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='roominvitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_invites_invitee_status', 'room_invites', ['invitee_id', 'status'], unique=False)
    op.create_index('ix_room_invites_room_invitee_status', 'room_invites', ['room_id', 'invitee_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_invites_room_invitee_status', table_name='room_invites')
    op.drop_index('ix_room_invites_invitee_status', table_name='room_invites')
    op.drop_table('room_invites')
    # ### end Alembic commands ###
